version: '3.8'
services:
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
  
  todoapp:
    build: ./todoapp
    ports:
      - 8000:8000
    depends_on:
      - mysql_db
    command: bash -c "/usr/wait.sh --timeout=0 mysql_db:3306 && php artisan migrate && php artisan serve --host 0.0.0.0"
  
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - todoapp
    links:
      - todoapp

volumes:
  my-db: